FROM golang:1.25.7-alpine AS builder

ARG GOOSE_VERSION=v3.27.3

RUN CGO_ENABLED=0 go install \
    -tags='no_clickhouse no_libsql no_mssql no_postgres no_sqlite3 no_vertica no_ydb' \
    github.com/pressly/goose/v3/cmd/goose@${GOOSE_VERSION}

FROM alpine:3.22

RUN addgroup -S migrator && adduser -S -G migrator migrator

WORKDIR /app
COPY --from=builder /go/bin/goose /usr/local/bin/goose
COPY --chown=migrator:migrator migrations ./migrations

USER migrator

ENV GOOSE_MIGRATION_DIR=/app/migrations

ENTRYPOINT ["goose"]
CMD ["up"]
